#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SingledOutAndroid.Resource", IsApplication=true)]

namespace SingledOutAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::SingledOutAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int black = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int buttonblue = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int dark_blue = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int darkwhite = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int gray = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int light_blue = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int light_orange = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int menuButtonColor = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int orange = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int semitransparent = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int transparent = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonselector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ellipse1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ellipse2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ellipse3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int facebooklogin = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int googlelogin = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logonopin = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logopin = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int RoundedButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int SingledOutAppIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int singledoutlogo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int textcolour = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int twitterlogin = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int childlayout1 = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int containerlayout = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int ellipse = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int facebooklogin = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int googleLogin = 2131230725;
			
			// aapt resource value: 0x7f080011
			public const int imageView1 = 2131230737;
			
			// aapt resource value: 0x7f08000b
			public const int logonopin = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int pin = 2131230730;
			
			// aapt resource value: 0x7f080003
			public const int signIn = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int signinchildlayout = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int signincontainerlayout = 2131230721;
			
			// aapt resource value: 0x7f08000e
			public const int tutorial1 = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int tutorial1childlayout = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int tutorial1containerlayout = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int twitterLogin = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int welcomeDescription = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int welcomeTitle = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int welcomechildlayout = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Footer_Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SignIn = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SplashPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Tutorial1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Welcome = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int logoarrives = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int pindropsound = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
